"""
Template strings for different DAG types.

These templates provide the boilerplate code for ingestion, processing,
and orchestration DAGs generated by the create_dag.py script.
"""


def get_ingestion_dag_template(dag_id: str, domain: str, name: str, schedule: str, description: str, owner: str) -> str:
    """Generate an ingestion DAG template using dlt."""
    start_task_id = f"{domain}_start"
    ingest_task_id = f"{domain}_run_ingestion"
    validate_task_id = f"{domain}_validate_ingestion"
    end_task_id = f"{domain}_end"

    return f'''"""
Ingestion DAG for {domain} - {name}.

This DAG orchestrates data ingestion using dlt (data load tool).
The actual extraction and loading logic is defined in the dlt pipeline
located in include/{domain}/ingestion/.
"""

from datetime import datetime

import pendulum
from airflow.sdk import DAG, task
from structlog import get_logger

log = get_logger()


with DAG(
    dag_id="{dag_id}",
    description="{description}",
    start_date=pendulum.datetime(2025, 8, 1, tz="UTC"),
    schedule="{schedule}",
    catchup=False,
    tags=["{domain}", "ingestion"],
    owner="{owner}",
    doc_md="""
    # {{dag_id}} DAG

    ## Overview
    This DAG manages the ingestion of {name} data into the data warehouse.

    It uses **dlt (data load tool)** to orchestrate the extraction, transformation,
    and loading of data from source systems.

    ## Task Flow
    1. `{start_task_id}` - Start marker
    2. `{ingest_task_id}` - Run the dlt ingestion pipeline
    3. `{validate_task_id}` - Validate the ingestion results
    4. `{end_task_id}` - End marker

    ## Configuration
    - **Domain**: {domain}
    - **Data Source**: {name}
    - **Schedule**: {schedule}
    - **Owner**: {owner}

    ## Pipeline Code
    The dlt pipeline and source definitions are located in:
    - `include/{domain}/ingestion/pipeline.py`
    - `include/{domain}/ingestion/sources.py`

    ## Secrets and Configuration
    All sensitive configuration (API keys, credentials, connection strings)
    should be managed via:
    - Airflow Connections
    - Airflow Variables
    - Environment variables
    - Azure Key Vault (if using Azure)
    - Google Cloud Secret Manager (if using GCP)

    Do NOT hard-code secrets in the DAG or pipeline code.
    """,
) as dag:

    @task
    def start():
        """Start task."""
        log.info("Starting {{dag_id}} ingestion")

    @task
    def run_ingestion():
        """
        Run the dlt ingestion pipeline.

        This task imports and executes the dlt pipeline defined in
        include/{domain}/ingestion/pipeline.py.

        TODO: Configure the dlt pipeline with appropriate:
        - Source (data location, API, credentials)
        - Destination (data warehouse, credentials)
        - Resource configuration (tables, schema, transformations)
        """
        # Example dlt pipeline invocation (adapt to your pipeline):
        # from include.{domain}.ingestion.pipeline import run_ingestion as dlt_run
        # load_info = dlt_run()
        # log.info(f"Ingestion completed: {{load_info}}")

        log.info("TODO: Implement dlt pipeline invocation for {domain}_{name}")
        raise NotImplementedError(
            "Pipeline not yet configured. "
            "Configure the dlt source and destination in include/{domain}/ingestion/pipeline.py"
        )

    @task
    def validate():
        """
        Validate the ingestion results.

        Check that:
        - Required tables were created
        - Expected row counts match
        - Data quality checks pass
        - No null values in critical columns
        """
        log.info("Validating {{dag_id}} ingestion results")
        # TODO: Add validation logic

    @task
    def end():
        """End task."""
        log.info("Completed {{dag_id}} ingestion")

    start() >> run_ingestion() >> validate() >> end()
'''


def get_processing_dag_template(
    dag_id: str, domain: str, name: str, schedule: str, description: str, owner: str
) -> str:
    """Generate a processing DAG template."""
    extract_task_id = f"{domain}_extract_{name}"
    transform_task_id = f"{domain}_transform_{name}"
    validate_task_id = f"{domain}_validate_{name}"
    publish_task_id = f"{domain}_publish_{name}"

    return f'''"""
Processing DAG for {domain} - {name}.

This DAG handles the transformation and enrichment of {name} data.
"""

from datetime import datetime

import pendulum
from airflow.sdk import DAG, task
from structlog import get_logger

log = get_logger()


with DAG(
    dag_id="{dag_id}",
    description="{description}",
    start_date=pendulum.datetime(2025, 8, 1, tz="UTC"),
    schedule="{schedule}",
    catchup=False,
    tags=["{domain}", "processing"],
    owner="{owner}",
    doc_md="""
    # {{dag_id}} DAG

    ## Overview
    This DAG handles transformation and enrichment of {name} data.

    ## Task Flow
    1. `{extract_task_id}` - Extract raw data
    2. `{transform_task_id}` - Transform and enrich the data
    3. `{validate_task_id}` - Validate the transformed data
    4. `{publish_task_id}` - Publish to target systems

    ## Configuration
    - **Domain**: {domain}
    - **Data Name**: {name}
    - **Schedule**: {schedule}
    - **Owner**: {owner}
    """,
) as dag:

    @task
    def extract():
        """Extract raw data from the source."""
        log.info("Extracting {{dag_id}} data")
        # TODO: Implement extraction logic

    @task
    def transform():
        """Transform and enrich the extracted data."""
        log.info("Transforming {{dag_id}} data")
        # TODO: Implement transformation logic

    @task
    def validate():
        """Validate the transformed data."""
        log.info("Validating {{dag_id}} data")
        # TODO: Implement validation logic

    @task
    def publish():
        """Publish the processed data."""
        log.info("Publishing {{dag_id}} data")
        # TODO: Implement publish logic

    extract() >> transform() >> validate() >> publish()
'''


def get_orchestration_dag_template(
    dag_id: str, domain: str, name: str, schedule: str, description: str, owner: str
) -> str:
    """Generate an orchestration DAG template."""
    start_task_id = f"{domain}_start"
    trigger_ingest_task_id = f"{domain}_trigger_{name}_ingestion"
    wait_ingest_task_id = f"{domain}_wait_{name}_ingestion"
    trigger_process_task_id = f"{domain}_trigger_{name}_processing"
    wait_process_task_id = f"{domain}_wait_{name}_processing"
    end_task_id = f"{domain}_end"

    return f'''"""
Orchestration DAG for {domain} - {name}.

This DAG coordinates and orchestrates other DAGs for {name} processing.
It does not contain business logic but rather orchestrates the execution
of ingestion and processing DAGs.
"""

from datetime import datetime

import pendulum
from airflow.sdk import DAG, task
from airflow.decorators import dag_decorator
from structlog import get_logger

log = get_logger()


with DAG(
    dag_id="{dag_id}",
    description="{description}",
    start_date=pendulum.datetime(2025, 8, 1, tz="UTC"),
    schedule="{schedule}",
    catchup=False,
    tags=["{domain}", "orchestration"],
    owner="{owner}",
    doc_md="""
    # {{dag_id}} DAG

    ## Overview
    This orchestration DAG coordinates the execution of {name}-related pipelines.

    It manages the execution order and dependencies of:
    - Ingestion DAGs (pulling data from sources)
    - Processing DAGs (transforming and enriching data)
    - Quality checks
    - Downstream notifications

    ## Task Flow
    1. `{start_task_id}` - Start marker
    2. `{trigger_ingest_task_id}` - Trigger the {name} ingestion DAG
    3. `{wait_ingest_task_id}` - Wait for ingestion to complete
    4. `{trigger_process_task_id}` - Trigger the {name} processing DAG
    5. `{wait_process_task_id}` - Wait for processing to complete
    6. `{end_task_id}` - End marker

    ## Configuration
    - **Domain**: {domain}
    - **Data Name**: {name}
    - **Schedule**: {schedule}
    - **Owner**: {owner}

    ## Dependencies
    - `{domain}_{name}_ingestion` DAG
    - `{domain}_{name}_processing` DAG
    """,
) as dag:

    @task
    def start():
        """Start task."""
        log.info("Starting {{dag_id}} orchestration")

    @task
    def trigger_ingestion():
        """
        Trigger the ingestion DAG.

        TODO: Configure the external DAG trigger to match your environment.
        Adapt this to use TriggerDagRunOperator or ExternalTaskSensor
        based on your Airflow version and setup.
        """
        log.info("Triggering {{dag_id}} ingestion pipeline")
        # Example using ExternalTaskSensor (waits for task in another DAG):
        # from airflow.sensors.external_task import ExternalTaskSensor
        # sensor = ExternalTaskSensor(
        #     task_id='wait_ingestion',
        #     external_dag_id='{domain}_{name}_ingestion',
        #     external_task_id='{domain}_run_ingestion',
        #     poke_interval=60,
        # )
        # TODO: Implement external DAG coordination

    @task
    def wait_ingestion():
        """Wait for ingestion to complete."""
        log.info("Waiting for {{dag_id}} ingestion to complete")
        # TODO: Add external task sensor or trigger logic

    @task
    def trigger_processing():
        """Trigger the processing DAG."""
        log.info("Triggering {{dag_id}} processing pipeline")
        # TODO: Implement external DAG coordination

    @task
    def wait_processing():
        """Wait for processing to complete."""
        log.info("Waiting for {{dag_id}} processing to complete")
        # TODO: Add external task sensor or trigger logic

    @task
    def end():
        """End task."""
        log.info("Completed {{dag_id}} orchestration")

    start() >> trigger_ingestion() >> wait_ingestion() >> trigger_processing() >> wait_processing() >> end()
'''


def get_dlt_pipeline_template(domain: str, name: str) -> str:
    """Generate a dlt pipeline template."""
    resource_name = f"{domain}_{name}"
    return f'''"""
dlt pipeline for {resource_name} ingestion.

This module defines the data extraction, transformation, and loading logic
for the {resource_name} dataset using dlt (data load tool).

Configuration (API keys, credentials, etc.) should be provided via:
- Environment variables
- Airflow Connections
- Airflow Variables
- dlt secrets.toml or config.toml
- Azure Key Vault
- Google Cloud Secret Manager
"""

import dlt
from .sources import {resource_name}_source


@dlt.resource(name="{resource_name}")
def {resource_name}_resource():
    """
    Fetch {resource_name} data from the source.

    TODO: Implement this function to:
    1. Configure the data source (API, database, file, etc.)
    2. Handle authentication and credentials securely
    3. Extract the required data
    4. Return data as dictionaries or pandas DataFrames

    Example:
        ```python
        yield {{"id": 1, "name": "example"}}
        ```
    """
    # Placeholder implementation
    yield {{"id": 1, "name": "example", "domain": "{domain}", "object": "{name}"}}


def run_ingestion():
    """
    Run the {resource_name} ingestion pipeline.

    This function:
    1. Creates a dlt pipeline instance
    2. Configures the data source
    3. Loads data into the destination (data warehouse)
    4. Returns load information

    Returns:
        LoadInfo: dlt load information object
    """
    # Create a dlt pipeline
    pipeline = dlt.pipeline(
        pipeline_name="{resource_name}",
        destination="duckdb",  # TODO: Configure destination (snowflake, postgres, etc.)
        dataset_name="{resource_name}_raw",  # TODO: Set appropriate dataset name
    )

    # Run the pipeline with the resource
    load_info = pipeline.run({resource_name}_resource())

    return load_info


if __name__ == "__main__":
    # For testing the pipeline locally
    info = run_ingestion()
    print(info)
'''


def get_dlt_sources_template(domain: str, name: str) -> str:
    """Generate a dlt sources template."""
    resource_name = f"{domain}_{name}"
    return f'''"""
dlt source definitions for {resource_name} data.

This module defines the data source configuration and extraction logic.
"""

import dlt


@dlt.source
def {resource_name}_source():
    """
    Define the {resource_name} data source.

    TODO: Configure the data source with:
    - Connection details (API URL, database, file path, etc.)
    - Authentication credentials (API keys, tokens, username/password, etc.)
    - Any necessary configuration or parameters

    Returns:
        A dlt source object
    """
    # Placeholder implementation
    return None
'''
